Добавляет две функции
htmlacademy-javascript/2006935-kekstagram-26 pull request #2
Opened 2022-06-06 15:44 UTC by Stuloviv

2022-06-06 16:05 UTC, Dima-Dim requested changes
Не забывай смотреть на замечания линтера.

2022-06-06 16:05 UTC, Dima-Dim commented on js/main.js
> +    from = from+to;
Не нужно переписывать значения которые приходя в функцию, лучше создать новые внутри и работать с ними. Вообще переопределять ранее присвоенные значения не очень хорошая практика. Приходится следить за тем что в переменной в итоге, а ещё это может быть объект которые передаётся по ссылке и один участок кода может не рассчитывать на происходящие изменения.

2022-06-07 07:02 UTC, Stuloviv commented on js/main.js
> +    from = from+to;
Привет!
Извини, пожалуйста, не совсем понимаю.
Нужно ввести другие переменные внутри if для такой замены, а потом присвоить from и to полученные значения?
Или вообще не нужно использовать такой способ - менять местами и придумать другое поведение функции?

PS Честно говоря, со вчера думаю над формулировкой этого вопроса, так и не могу нормально сформулировать... ;)

2022-06-07 09:22 UTC, Dima-Dim commented on js/main.js
> +    from = from+to;
> Нужно ввести другие переменные внутри if для такой замены

Да, можно так. Можно определить их внутри функции, но не нужно переопределять то, что передано внутрь функции.

2022-06-07 09:29 UTC, Stuloviv commented on js/main.js
> +    from = from+to;
Спасибо! Попробую что получится))

2022-06-08 15:40 UTC, merged