Добавляет валидацию формы, закрытие формы
htmlacademy-javascript/2006935-kekstagram-26 pull request #7
Opened 2022-07-18 15:26 UTC by Stuloviv

2022-07-20 18:14 UTC, Dima-Dim requested changes

2022-07-20 18:14 UTC, Dima-Dim commented on js/img-upload-form.js
> +      Uncaught TypeError: evt.key.stopPropagation is not a function
Да, а почему у строки, котой является evt.key ты ожидаешь наличие метода stopPropagation?

2022-07-20 18:14 UTC, Dima-Dim commented on js/img-upload-form.js
> +// нельзя указать больше пяти хэш-тегов;
Это должно быть понятно из названия константы, в котой будет число 5, а не комментария.

2022-07-20 19:01 UTC, Stuloviv commented on js/img-upload-form.js
> +// нельзя указать больше пяти хэш-тегов;
Понял, Комментарии оставлял просто для удобства, что код для одной валидация тут, а код другой там...

2022-07-20 19:11 UTC, Stuloviv commented on js/img-upload-form.js
> +      Uncaught TypeError: evt.key.stopPropagation is not a function
Не понимаю.
Это же и есть событие... Если убрать evt.key, то ошибка другая:
Uncaught ReferenceError: stopPropagation is not defined at HTMLDocument

2022-07-20 19:16 UTC, Stuloviv commented on js/img-upload-form.js
> +      Uncaught TypeError: evt.key.stopPropagation is not a function
MDN говорит, что "Прекращает дальнейшую передачу текущего события."
evt.key текущее событие.

2022-07-20 19:45 UTC, Stuloviv commented on js/img-upload-form.js
> +      Uncaught TypeError: evt.key.stopPropagation is not a function
...Суть понял. Тогда пока не понимаю кто есть событие и кому устроить stopPropagation.

2022-07-21 11:28 UTC, Dima-Dim commented on js/img-upload-form.js
> +      Uncaught TypeError: evt.key.stopPropagation is not a function
Видимо `evt` и есть событие :)

2022-07-21 12:10 UTC, Stuloviv commented on js/img-upload-form.js
> +      Uncaught TypeError: evt.key.stopPropagation is not a function
Если оставить только evt, то ничего не работает. Есть что-то что я не понимаю

2022-07-21 19:10 UTC, Dima-Dim commented on js/img-upload-form.js
> +      Uncaught TypeError: evt.key.stopPropagation is not a function
Вижу что разобрался как правильно использовать evt, в частности `preventDefault()`?

2022-07-21 19:14 UTC, Dima-Dim commented on js/img-upload-form.js
> +  const arr = [];
https://up.htmlacademy.ru/javascript/26/criteries#b8 даже если это временный и совсем не важный массив, называть его нужно правильно и осознанно :)

2022-07-21 19:14 UTC, Dima-Dim commented on js/img-upload-form.js
> +  return value.length <= 140;
140 здесь это магическое число и его лучше вынести в константу.

2022-07-21 19:14 UTC, merged

2022-07-21 19:18 UTC, Dima-Dim commented on js/img-upload-form.js
> +const hashtagsQuantity = 5;
https://up.htmlacademy.ru/javascript/26/criteries#b7